import '@/styles/globals.css'
import type { Metadata } from 'next'
import { FC, PropsWithChildren } from 'react'
import { fontBarlow } from '@/styles/font'

export const metadata: Metadata = {
  title: 'Simple Next.js',
  description: 'Generated by Simple Next.js',
}

const RootLayout: FC<PropsWithChildren> = ({ children }) => (
  <html lang="en">
    <div className={fontBarlow.className}>
      {children}
    </div>
  </html>
)

export default RootLayout
